namespace SpriteKind {
    export const HITBOX = SpriteKind.create()
    export const CHEST = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    sprites.destroy(sprite)
    pause(100)
    game.setGameOverMessage(false, "GAME OVER!")
    game.gameOver(false)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (PLYR.isHittingTile(CollisionDirection.Bottom)) {
        PLYR.vy += -150
    }
})
function RespawnChests (num: number) {
    if (lava_level == 10 && info.score() <= 2) {
        for (let index = 0; index < num; index++) {
            CHESTS = sprites.create(assets.image`chest`, SpriteKind.CHEST)
            tiles.placeOnRandomTile(CHESTS, assets.tile`myTile2`)
        }
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (game.runtime() >= lasttimestamp && controller.right.isPressed()) {
        lasttimestamp = game.runtime()
        animation.runImageAnimation(
        PLYR,
        [img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fdddddd111df......
            ......fbddddddd1df......
            ......ffbbddbfd1df......
            .......fcbbdcfddbf......
            .......fffbddccffff.....
            .......ffffcfbbb1bcf....
            ......ffffffffcd1b1f....
            ...ffffffffff..fdfdf....
            .....ffffff.....f.f.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            .........fffff..........
            .......ffb1111ff........
            ......fb1111111bf.......
            ......f111111111f.......
            .....ffff1111111df......
            ....fb111c1dd111df......
            ....ffb1b1fdcf11bf......
            .....ffbfbfb11111f......
            ......ffffcfdb1b1f......
            .......fcccfcfbfbf......
            ........ffffffffff......
            .........ffffff.........
            .........ffffff.........
            .....f..fffffff.........
            .....fffffffff..........
            ......fffffff...........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fbddddbfd1df......
            ......fcbbbdcfddbf......
            .......fcbb11111f.......
            ........fffff1b1f.......
            ........fb111cfbf.......
            ........ffb1b1ff........
            ......f.fffbfbf.........
            ......ffffffff..........
            .......fffff............
            ........................
            ........................
            ........................
            ........................
            `],
        200,
        false
        )
        PLAYER_ATK = sprites.create(img`
            . . . f f f f . . . . . . . . . 
            . . . f 2 2 f f f f . . . . . . 
            . . . . f 2 2 2 2 f f . . . . . 
            . . . . . . f f 2 2 f . . . . . 
            . . . . . . . . f f 2 f . . . . 
            . . . . . . . . . . 2 2 f . . . 
            . . . . . . . . . . . 2 f . . . 
            . . . . . . . . . . f 2 f . . . 
            . . . . . . . . . . f 2 f . . . 
            . . . . . . . . . . f 2 f . . . 
            . . . . . . . . . f 2 f . . . . 
            . . . . . . . . f 2 2 f . . . . 
            . . . . . . f 2 2 2 f . . . . . 
            . . . . . f 2 2 f f . . . . . . 
            . . . . f 2 2 f . . . . . . . . 
            . . . . . f . . . . . . . . . . 
            `, SpriteKind.HITBOX)
    }
    if (game.runtime() >= lasttimestamp && controller.left.isPressed()) {
        lasttimestamp = game.runtime()
        animation.runImageAnimation(
        PLYR,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........fffff.........
            ........ff1111bff.......
            .......fb1111111bf......
            .......f111111111f......
            ......fd1111111ffff.....
            ......fd111dd1c111bf....
            ......fb11fcdf1b1bff....
            ......f11111bfbfbff.....
            ......f1b1bdfcffff......
            ......fbfbfcfcccf.......
            ......ffffffffff........
            .........ffffff.........
            .........ffffff.........
            .........fffffff..f.....
            ..........fffffffff.....
            ...........fffffff......
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f1111111dbf......
            ......fd1111111ddf......
            ......fd111111dddf......
            ......fd111ddddddf......
            ......fd111ddddddf......
            ......fd1dddddddbf......
            ......fd1dfbddbbff......
            ......fbddfcdbbcf.......
            .....ffffccddbfff.......
            ....fcb1bbbfcffff.......
            ....f1b1dcffffffff......
            ....fdfdf..ffffffffff...
            .....f.f.....ffffff.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        200,
        false
        )
        PLAYER_ATK = sprites.create(img`
            . . . . . . . f f f f f . . . . 
            . . . . . . f f f 2 2 . . . . . 
            . . . . . f f 2 2 2 f . . . . . 
            . . . . f 2 2 . . . . . . . . . 
            . . . f 2 2 f . . . . . . . . . 
            . . f 2 2 f . . . . . . . . . . 
            . f 2 2 2 . . . . . . . . . . . 
            . f 2 2 . . . . . . . . . . . . 
            . f 2 2 . . . . . . . . . . . . 
            . f 2 2 f . . . . . . . . . . . 
            . f f 2 . . . . . . . . . . . . 
            . . f 2 2 . . . . . . . . . . . 
            . . . f f 2 . . . . . . . . . . 
            . . . . f f f 2 2 f f . . . . . 
            . . . . . . f 2 2 . . . . . . . 
            . . . . . . . f f 2 f . . . . . 
            `, SpriteKind.HITBOX)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile7`, function (sprite, location) {
    sprites.destroy(sprite)
    pause(100)
    game.setGameOverMessage(false, "GAME OVER!")
    game.gameOver(false)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    PLYR,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
scene.onOverlapTile(SpriteKind.HITBOX, sprites.dungeon.chestClosed, function (sprite, location) {
    info.changeScoreBy(1)
    tiles.setTileAt(location, assets.tile`DARK`)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    PLYR,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
// TEACHER GIVEN CODE
sprites.onCreated(SpriteKind.HITBOX, function (sprite) {
    if (game.runtime() >= lasttimestamp && controller.right.isPressed()) {
        sprite.setPosition(PLYR.x + 15, PLYR.y)
    } else {
        sprite.setPosition(PLYR.x - 15, PLYR.y)
    }
    pause(100)
    sprites.destroy(sprite)
})
sprites.onOverlap(SpriteKind.HITBOX, SpriteKind.CHEST, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeScoreBy(1)
    sprites.destroy(sprite)
})
function LEVELCHANGE (num: number) {
    if (info.score() >= 10 && PLYR.tileKindAt(TileDirection.Bottom, sprites.dungeon.collectibleInsignia)) {
        if (true) {
            tiles.setCurrentTilemap(MAPS.removeAt(0))
        }
    }
    if (info.score() >= 20 && PLYR.tileKindAt(TileDirection.Bottom, sprites.dungeon.collectibleInsignia)) {
        if (true) {
            tiles.setCurrentTilemap(MAPS.removeAt(0))
        }
    }
    if (info.score() >= 30 && PLYR.tileKindAt(TileDirection.Bottom, sprites.dungeon.collectibleInsignia)) {
        game.setGameOverMessage(true, "YOU WIN")
        game.gameOver(true)
    }
}
let PLAYER_ATK: Sprite = null
let CHESTS: Sprite = null
let lava_level = 0
let MAPS: tiles.TileMapData[] = []
let PLYR: Sprite = null
let lasttimestamp = 0
lasttimestamp = game.runtime()
tiles.setCurrentTilemap(tilemap`level1`)
PLYR = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......fd1111111f.......
    ......fdd1111111df......
    ......fddd111111df......
    ......fdddddd111df......
    ......fbddddbfd1df......
    ......fcbbbdcfddbf......
    .......fcbb11111f.......
    ........fffff1b1f.......
    ........fb111cfbf.......
    ........ffb1b1ff........
    ......f.fffbfbf.........
    ......ffffffff..........
    .......fffff............
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
tiles.placeOnTile(PLYR, tiles.getTileLocation(11, 45))
PLYR.ay = 300
controller.moveSprite(PLYR, 100, 0)
scene.cameraFollowSprite(PLYR)
let TIME = 4000
MAPS = [tilemap`level0`, tilemap`level18`]
game.onUpdateInterval(TIME, function () {
    lava_level += 1
    for (let index = 0; index <= 36; index++) {
        tiles.setTileAt(tiles.getTileLocation(index, lava_level * -1 + 56), assets.tile`myTile1`)
    }
    RespawnChests(4)
    LEVELCHANGE(1)
})
